# Generated by Django 4.1.7 on 2023-05-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='avatares/default.jpg', null=True, upload_to='avatares'),
        ),
    ]
