# Generated by Django 4.1.7 on 2023-05-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteocreado',
            name='imagen',
        ),
    ]
