# Generated by Django 4.1.7 on 2023-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0006_remove_posteocreado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteocreado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posteos'),
        ),
    ]
