# Generated by Django 4.1.7 on 2023-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0007_posteocreado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteocreado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/posteos'),
        ),
    ]
